### ISSUE TITLE
Implement Handlers for users repository

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#12]
# Description:
We need to implement handler for the users repository. 

## Tasks:

**Users Handler:**
   - [x] implement the user handler.
   - [x] Integrate the user handler with the repository layer.
   - [x] use clean architecture pattern

**Acceptance Criteria:**
- [x] Handlers for users is implemented.
- [x] Each handler is integrated with the repository layer.
- [x] Unit tests for each handler are comprehensive and pass.
