### ISSUE TITLE
Implement Handlers for posts repository

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#13]
# Description:
We need to implement handler for the posts repository. 

## Tasks:

**Users Handler:**
   - [x] implement the posts handler.
   - [x] Integrate the posts handler with the repository layer.
   - [x] use clean architecture pattern

**Acceptance Criteria:**
- [x] Handlers for posts is implemented.
- [x] Each handler is integrated with the repository layer.
- [x] Unit tests for each handler are comprehensive and pass.

**Comment by minierparedes** [comment]
-
