### ISSUE TITLE
Implement Handlers for page repository

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#14]
# Description:
We need to implement handler for the page repository. 

## Tasks:

**Users Handler:**
   - [x] implement the page handler.
   - [x] Integrate the page handler with the repository layer.
   - [x] use clean architecture pattern

**Acceptance Criteria:**
- [x] Handlers for page is implemented.
- [x] Each handler is integrated with the repository layer.
- [x] Unit tests for each handler are comprehensive and pass.
