### ISSUE TITLE
Implement Handlers for meta repository

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#15]
# Description:
We need to implement handler for the meta repository. 

## Tasks:

**Users Handler:**
   - [ ] implement the meta handler.
   - [ ] Integrate the meta handler with the repository layer.
   - [ ] use clean architecture pattern

**Acceptance Criteria:**
- [ ] Handlers for meta is implemented.
- [ ] Each handler is integrated with the repository layer.
- [ ] Unit tests for each handler are comprehensive and pass.

**Comment by minierparedes** [comment]
The following [PR](https://github.com/minierparedes/frog-blossom-cms/pull/47) was created in error.
Per the clarification on [slack discussion](https://reflectionizm.slack.com/archives/C076E1SGWBS/p1718935521863789)
