### ISSUE TITLE
Remove Table ID from table Responses

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#23]
# Description:

Update the server-side handler to exclude the table ID from the responses for pages.
Currently pages table is the one being found but the other tables may also be returning their table id.
Other tables need to checked.

reference:

```bash
curl -X POST \
   http://localhost:8080/api/v1/create-page \
  -H 'Content-Type: application/json' \
  -d '{
    "domain": "example.com",
    "author_id": 123,
    
    {"id":170,"domain":"example.com","author_id":123,"page_author":"yfupof"
```

**Tasks:**
- [ ] Modify the database query to exclude the table ID for pages.
- [ ] Confirm and other tables are excluding their table ID. 
- [ ] Update the handler function to ensure the table ID is not included in the response.
- [ ] Test the changes to ensure the table ID is no longer returned.

**Acceptance Criteria:**
- [ ] Table ID is excluded from all table responses.
- [ ] Handler function correctly omits the table ID.
- [ ] All relevant tests pass.
