### ISSUE TITLE
Fix Comparison of Wrapped Errors Using Equality Operators

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#29]
# Description:

Resolve issue where comparing wrapped errors using equality operators fails.

error: `Comparison with errors using equality operators fails on wrapped errors `

```go
if err != nil {
		if err == sql.ErrNoRows {
			ctx.JSON(http.StatusBadRequest, errorResponse(err))
			return
		}
	}
}
 ```

**Tasks:**
- [ ] Identify instances where wrapped errors are compared using equality operators.
- [ ] Replace equality comparisons with `errors.Is` to correctly handle wrapped errors.
- [ ] Test to ensure error comparisons work as expected.

**Acceptance Criteria:**
- [ ] All instances of error comparisons use `errors.Is`.
- [ ] Error comparisons correctly handle wrapped errors.
- [ ] All relevant tests pass.
