### ISSUE TITLE
Refactor Handlers to Include Associated Meta Data

### ISSUE THREAD

**Issue by minierparedes** [minierparedes/frog-blossom-db#49]
# Description:

Refactor the handlers to ensure that the `get` and `list` endpoints for posts and pages also retrieve their respective associated meta data.

**Tasks:**
- [ ] Update `ListPagesHandler` to include associated meta data.
- [ ] Update `GetPageHandler` to include associated meta data.
- [ ] Update `ListPostsHandler` to include associated meta data.
- [ ] Update `GetPostHandler` to include associated meta data.
- [ ] Test all updated handlers to ensure they correctly retrieve and return associated meta data.

**Acceptance Criteria:**
- [ ] `ListPagesHandler` includes associated meta data.
- [ ] `GetPageHandler` includes associated meta data.
- [ ] `ListPostsHandler` includes associated meta data.
- [ ] `GetPostHandler` includes associated meta data.
- [ ] Handlers are tested and confirmed to return the correct data.
